name: Build CoA manifest
on:
  schedule:
    - cron: "0 18 * * *"  # 每日 02:00 (台灣) 左右
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build manifest
        run: node scripts/build-manifest.mjs

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain docs/manifest)" ]; then
            git add docs/manifest
            git commit -m "chore: update CoA manifest [skip ci]"
            git push
          else
            echo "No changes."
          fi
